image: Visual Studio 2017

platform:
  - x64

# cache:
  # Not caching node_modules because appveyor doesn't restore it afterwards (not sure why)
  # - node_modules
  # - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - npm install
  - ps: cd ElectronClient
  - yarn dist

test: off

# We only want to build tags
skip_non_tags: true