version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: app
    container_name: app
    #restart: unless-stopped
    #env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    # ports:
    #   - "80:8080"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    # networks:
    #   - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
