name: 'Close stale issues'
on:
  schedule:
    - cron: '0 16 * * *'
permissions:
  issues: write
jobs:
  ProcessStaleIssues:
    if: github.repository == 'laurent22/joplin'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # Use this to do a dry run from a pull request
          # debug-only: true
          stale-issue-message: "Hey there, it looks like there has been no activity on this issue recently. Has the issue been fixed, or does it still require the community's attention? If you require support or are requesting an enhancement or feature then please create a topic on the [Joplin forum](https://discourse.joplinapp.org/). This issue may be closed if no further activity occurs. You may comment on the issue and I will leave it open. Thank you for your contributions."
          days-before-stale: 30
          days-before-close: 7
          operations-per-run: 1000
          exempt-issue-labels: 'good first issue,upstream,backlog,high,medium,spec,cannot reproduce,enhancement'
          stale-issue-label: 'stale'
          close-issue-message: 'Closing this issue after a prolonged period of inactivity. If this issue is still present in the latest release, feel free to create a new issue with up-to-date information.'
          # Don't process pull requests at all
          days-before-pr-stale: -1
